### ISSUE TITLE
video home page style

### ISSUE THREAD

**Issue by lfrancois** [trackit/amplify-video-community#41]
update the UI for the video homepage to match figma created by @MarlonLH

**Comment by YFloris** [comment]
Video page has been updated by @JulienMeziere, we now need to improve the video player page and the category video page ("see all" button)

**Comment by JulienMeziere** [comment]
If it works well, it switches to light theme when you scroll down on the home page
It is dark theme at the top of the home page to let the user see the background video

**Comment by ewinett** [comment]
Est. completion date is Monday October 4th
