### ISSUE TITLE
deploy process for community website documentation

### ISSUE THREAD

**Issue by lfrancois** [trackit/amplify-video-community#43]
Make sure we have the process documented in case we want to publish the community website in a more official amplify-video project domain.

**Comment by lfrancois** [comment]
amplify-video.com domain is owned by Sam, should we plan to deploy there?

**Comment by smp** [comment]
Site code hosted on aws-samples likely. will try to get .aws domain, if not possible will use amplify-video.com

**Comment by ewinett** [comment]
Est. completion date is Monday/Tuesday September 27/28
