### ISSUE TITLE
written blog tutorial on how to build community site

### ISSUE THREAD

**Issue by smp** [trackit/amplify-video-community#50]
text companion to #45 that can be posted on aws media blog and track.it blog along with video link

**Comment by lfrancois** [comment]
Here is the document we need to update:
- https://docs.google.com/document/d/19dfJtldVJaqXHf9GoAgRqDDL0hb-g09UDGXRIpv3Qrk/edit?usp=sharing

**Comment by ewinett** [comment]
Est. completion date is Monday Oct 4th

**Comment by YFloris** [comment]
Missing:
- [ ] Architecture diagram
- [ ] Sub-domain management
- [ ] Update models
- [ ] Finish the admin dashboard part
